### ISSUE TITLE
v5.0.0 killing homebridge

### ISSUE THREAD

**Issue by mensa84** [plasticrake/homebridge-tplink-smarthome#110]
Hello,

I ran v4.0.1 without problems. After upgrading to v5.0.0 I always get that errors and homebridge keeps restarting:

```
Jan 10 09:22:58 Server systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Jan 10 09:22:58 Server systemd[1]: homebridge.service: Failed with result 'exit-code'.

```

When I downgrade to v4.0.1 everything is fine again.
Could you please fix that?

My config for that plugin is only:

```
{
	"platform": "TplinkSmarthome",
	"name": "TplinkSmarthome"
}
```

**Comment by ksmulders** [comment]
Hi Mensa, I have the same problem. Reinstalling Homebridge and the plugin seems to work, but none of my devices can be found, execpt for the bulbs. When adding the bulb, I receive a UUID-error.

**Comment by slayer1551** [comment]
Hi all, getting same error. Looking at the output this is what happening

`TypeError: Cannot read property 'UUID' of undefined
    at HomeKitDevicePlug.getCharacteristic (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/homekit-device/index.js:75:48)
    at HomeKitDevicePlug.supportsCharacteristic (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/homekit-device/index.js:58:17)
    at characteristics.forEach.characteristic (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/tplink-accessory.js:181:25)
    at Array.forEach (<anonymous>)
    at TplinkAccessory.setupCharacteristics (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/tplink-accessory.js:180:21)
    at new TplinkAccessory (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/tplink-accessory.js:110:12)
    at createTplinkAccessory (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/platform.js:74:10)
    at TplinkSmarthomePlatform.addAccessory (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/platform.js:252:23)
    at Client.TplinkSmarthomePlatform.client.on.device (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/platform.js:132:12)
    at Client.emit (events.js:189:13)
    at Client.emit (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:191:13)
    at process (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:604:14)
    at Client.createOrUpdateDeviceFromSysInfo (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:614:7)
    at Socket.socket.on (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:529:14)
    at Socket.emit (events.js:189:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)`

**Comment by mensa84** [comment]
@slayer1551 Why do you see more logs of it? Are you using any other command than `journalctl -f -u homebridge` to get that output above?

**Comment by slayer1551** [comment]
> @slayer1551 Why do you see such detailed logs of it? Are you using any other command than `journalctl -f -u homebridge` to get that output above?

I'm running /homebridge directly in the console window on my Pi to see whats being output

**Comment by schweppy** [comment]
Also for me, have removed until there’s a fix.

**Comment by marksthomas** [comment]
Same here. Buggered. How do I install v4.0.1 again?

**Comment by plasticrake** [comment]
I've pulled the release for now

**Comment by mrjackyliang** [comment]
Have the same UUID error since the update. Already downgraded.
