### ISSUE TITLE
Error: TCP Socket Closed

### ISSUE THREAD

**Issue by kkrankall** [plasticrake/homebridge-tplink-smarthome#132]
### Expected Behavior
Setting up my Kasa KP400 Switches in Homebridge

### Current Behavior
Getting TCP Socket Closed Error

### Steps to Reproduce (for bugs)

Does it when the service tries to start

### Versions

- **Node**:       `12.18.2`
- **Homebridge**: `1.1.1`
- **OS**:         `Raspbian GNU/Linux Buster (10)`

### Configuration

```{
    "bridge": {
        "name": "Homebridge 9999",
        "username": "99:99:99:99:99:99",
        "port": 51813,
        "pin": "XXX-XX-XXXX"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "platform": "TplinkSmarthome",
            "name": "TplinkSmarthome",
            "timeout": 20
        },
        {
            "refreshToken": "sensitive data",
            "platform": "Ring"
        }
    ]
}
```

### Homebridge Log / Command Output

```[7/1/2020, 10:19:46 PM] Homebridge is running on port 51813.
[7/1/2020, 10:19:46 PM] [TplinkSmarthome] New Device Online: [Patio Lights] plug [8006F17939B3395F010234A7454D2B831B8B394200] 10.0.1.78 9999
[7/1/2020, 10:19:46 PM] [TplinkSmarthome] Adding: [Patio Lights] plug [8006F17939B3395F010234A7454D2B831B8B394200]
[7/1/2020, 10:19:47 PM] [TplinkSmarthome] New Device Online: [Harlows Doghouse] plug [8006F17939B3395F010234A7454D2B831B8B394201] 10.0.1.78 9999
[7/1/2020, 10:19:47 PM] [TplinkSmarthome] Adding: [Harlows Doghouse] plug [8006F17939B3395F010234A7454D2B831B8B394201]
[7/1/2020, 10:19:48 PM] [TplinkSmarthome] New Device Online: [Ring Porch] plug [8006F378A3161903CBB926451295738A1C490B6C00] 10.0.1.77 9999
[7/1/2020, 10:19:48 PM] [TplinkSmarthome] Adding: [Ring Porch] plug [8006F378A3161903CBB926451295738A1C490B6C00]
[7/1/2020, 10:19:49 PM] [TplinkSmarthome] New Device Online: [Bug Zapper] plug [8006F378A3161903CBB926451295738A1C490B6C01] 10.0.1.77 9999
[7/1/2020, 10:19:49 PM] [TplinkSmarthome] Adding: [Bug Zapper] plug [8006F378A3161903CBB926451295738A1C490B6C01]
[7/1/2020, 10:19:54 PM] [Ring] Configuring 4 cameras and 5 devices for location ...
[7/1/2020, 10:20:04 PM] [TplinkSmarthome.API] TCP 10.0.1.78:9999 Error: TCP Socket Closed. segment:0 hadError:false
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:113:19)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
[7/1/2020, 10:20:04 PM] [TplinkSmarthome] [Harlows Doghouse] 
[7/1/2020, 10:20:04 PM] [TplinkSmarthome] Error: TCP Socket Closed. segment:0 hadError:false
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:113:19)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
[7/1/2020, 10:20:04 PM] [TplinkSmarthome.API] TCP 10.0.1.77:9999 Error: TCP Socket Closed. segment:0 hadError:false
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:113:19)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
[7/1/2020, 10:20:04 PM] [TplinkSmarthome] [Ring Porch] 
[7/1/2020, 10:20:04 PM] [TplinkSmarthome] Error: TCP Socket Closed. segment:0 hadError:false
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:113:19)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
[7/1/2020, 10:20:04 PM] [TplinkSmarthome.API] TCP 10.0.1.77:9999 Error: TCP Socket Closed. segment:0 hadError:false
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:113:19)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
[7/1/2020, 10:20:04 PM] [TplinkSmarthome] [Bug Zapper] 
[7/1/2020, 10:20:04 PM] [TplinkSmarthome] Error: TCP Socket Closed. segment:0 hadError:false
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:113:19)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
[7/1/2020, 10:20:04 PM] [TplinkSmarthome.API] TCP 10.0.1.78:9999 Error: TCP Socket Closed. segment:0 hadError:false
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:113:19)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
[7/1/2020, 10:20:04 PM] [TplinkSmarthome] [Patio Lights] 
[7/1/2020, 10:20:04 PM] [TplinkSmarthome] Error: TCP Socket Closed. segment:0 hadError:false
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:113:19)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
```

**Comment by kkrankall** [comment]
Put Homebridge in debug mode

Here some data from logs...

```[7/2/2020, 3:53:39 PM] [TplinkSmarthome.API] client.startDiscovery(): socket:message From: 10.0.1.78 9999 Message: {"system":{"get_sysinfo":{"sw_ver":"1.0.10 Build 190716 Rel.095026","hw_ver":"1.0","model":"KP400(US)","deviceId":"8006F17939B3395F010234A7454D2B831B8B3942","oemId":"FD4F485EDD720B0D70958563B7ABEF4F","hwId":"85ED17594C2838F50BE6EAE5E26C29A8","rssi":-58,"longitude_i":-734781,"latitude_i":412099,"alias":"TP-LINK_Smart Plug_EED4","status":"new","mic_type":"IOT.SMARTPLUGSWITCH","feature":"TIM","mac":"98:DA:C4:0C:EE:D4","updating":0,"led_off":0,"children":[{"id":"00","state":0,"alias":"Patio Lights","on_time":0,"next_action":{"type":-1}},{"id":"01","state":1,"alias":"Harlows Doghouse","on_time":98240,"next_action":{"type":-1}}],"child_num":2,"ntc_state":0,"err_code":0}},"emeter":{"err_code":-1,"err_msg":"module not support"},"smartlife.iot.common.emeter":{"err_code":-1,"err_msg":"module not support"}}
[7/2/2020, 3:53:39 PM] [TplinkSmarthome.API] [TP-LINK_Smart Plug_EED4] device sysInfo set
[7/2/2020, 3:53:39 PM] [TplinkSmarthome.API] [Patio Lights] plug sysInfo set
[7/2/2020, 3:53:39 PM] [TplinkSmarthome.API] [Patio Lights] plug.emitEvents() inUse: false relayState: false lastState: {"inUse":false,"relayState":false}
[7/2/2020, 3:53:39 PM] [TplinkSmarthome] Device Online: [Patio Lights] plug [8006F17939B3395F010234A7454D2B831B8B394200] 10.0.1.78 9999
[7/2/2020, 3:53:39 PM] [TplinkSmarthome.API] [TP-LINK_Smart Plug_EED4] device sysInfo set
[7/2/2020, 3:53:39 PM] [TplinkSmarthome.API] [Harlows Doghouse] plug sysInfo set
[7/2/2020, 3:53:39 PM] [TplinkSmarthome.API] [Harlows Doghouse] plug.emitEvents() inUse: true relayState: true lastState: {"inUse":true,"relayState":true}
[7/2/2020, 3:53:39 PM] [TplinkSmarthome] Device Online: [Harlows Doghouse] plug [8006F17939B3395F010234A7454D2B831B8B394201] 10.0.1.78 9999
```

**Comment by kkrankall** [comment]
So don't know why but everything is working fine as of today. Even rebooted the Homebridge service to make sure if was fixed.
