### ISSUE TITLE
Plugin causing SIGTERM: Object.parseConfig (/usr/lib/node_modules/homebridge-tplink-smarthome/src/config.ts

### ISSUE THREAD

**Issue by jakehawkes** [plasticrake/homebridge-tplink-smarthome#166]
### Expected Behavior
Plugin is crashing, bringing down entire HomeBridge.

### Current Behavior
Not sure what happened, but "all of a sudden" my HomeBridge setup stopped working. I checked the logs, and found that it was this plugin.

### Steps to Reproduce (for bugs)
Not sure what to say. It was working one day and not the next.

### Versions

- **Node**:       `node --version`: v14.15.1

- **Homebridge**: `homebridge --version`: 1.2.3

- **OS**:         
   - `uname -a`: Linux homepi 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux
   - `cat /etc/debian_version`: 10.6

### Configuration

```json
        {
            "platform": "TplinkSmarthome",
            "name": "TplinkSmarthome"
        },
```

### Homebridge Log / Command Output

```
[14/12/2020, 11:52:12] [TplinkSmarthome] homebridge-tplink-smarthome v6.1.0, node v14.15.1, homebridge v1.2.3
[14/12/2020, 11:52:13] TypeError: 
    at Object.parseConfig (/usr/lib/node_modules/homebridge-tplink-smarthome/src/config.ts:165:52)
    at new TplinkSmarthomePlatform (/usr/lib/node_modules/homebridge-tplink-smarthome/src/platform.ts:69:19)
    at /usr/lib/node_modules/homebridge/src/server.ts:395:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

On a whim, I checked the homebridge config, and tried removing the following line:
```json
"switchModels": "HS103"
```

And it seems to have worked. This is what I saw in the log:
```
14/12/2020, 11:57:00] [TplinkSmarthome] New Device Online: [White Lights] plug [8006xxxxxx54BA] 192.168.x.x 9999
[14/12/2020, 11:57:00] [TplinkSmarthome] Adding: [White Lights] plug [8006xxxxxx54BA]
[14/12/2020, 11:57:00] [TplinkSmarthome] [White Lights] Correcting Accessory Category from: SWITCH to: OUTLET
HAP Warning: Characteristic E863F126-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic E863F10C-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic E863F110-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic E863F10A-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic E863F10D-079E-48FF-8F27-9C2605A29F52 not in required or optional characteristics for service 00000047-0000-1000-8000-0026BB765291. Adding anyway.

**Comment by plasticrake** [comment]
`switchModels` takes an array, not a string. Also HS103 is not a wall switch, it is an outlet. Now that you've removed that incorrect configuration it appears to be working fine, correct?

**Comment by jakehawkes** [comment]
Yes. We can probably close the issue, although, it would be nice if the plugin didn't crash and take down HB... Call it a wishlist item.

**Comment by plasticrake** [comment]
I've added validation #195
