### ISSUE TITLE
State not updating on plugs, switch randomly erroring

### ISSUE THREAD

**Issue by genebean** [plasticrake/homebridge-tplink-smarthome#168]
### Expected Behavior

With solid network connectivity and unchanged IP addresses, I expect that state should be reported correctly and there should not be TCP timeouts.

### Current Behavior

I have a couple of HS105 plugs (firmware version 1.5.6) that seldom have the correct state reported. Toggling them on or off via Homebridge also seems very hit or miss. Additionally, I am regularly seeing the errors below on a HS210 switch (firmware 1.5.8):

```bash
[19/12/2020, 08:57:10] [TplinkSmarthome] Error: TCP Timeout after 15000ms
192.168.16.116:9999 {"system":{"get_sysinfo":{}}}
[19/12/2020, 08:57:25] [TplinkSmarthome.API] TCP 192.168.16.116:9999 Error: TCP Timeout after 15000ms
192.168.16.116:9999 {"system":{"get_sysinfo":{}}}
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:67:17)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[19/12/2020, 08:57:25] [TplinkSmarthome.API] [Kitchen Light] device.send() Error: TCP Timeout after 15000ms
192.168.16.116:9999 {"system":{"get_sysinfo":{}}}
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:67:17)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

Both devices work just fine at all times in the Kasa app.

### Versions

```bash
pi@homebridge:/var/lib/homebridge $ node --version
v14.15.1
pi@homebridge:/var/lib/homebridge $ homebridge --version
1.1.7
pi@homebridge:/var/lib/homebridge $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

### Configuration

```json
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "broadcast": "192.168.16.255",
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome"
        }
```

Relevant for my config as all TP Link devices are on the 192.168.16.0/24 network:

```bash
pi@homebridge:/var/lib/homebridge $ ip route
default via 192.168.15.1 dev eth0 
192.168.15.0/24 dev eth0 proto kernel scope link src 192.168.15.11 
192.168.16.0/24 dev eth0.16 proto kernel scope link src 192.168.16.222
```

**Comment by rakeshnsw** [comment]
I recently updated homebridge and homebridge-tplink-smarthome plugin. I am facing the same issue. I have some HS103 and HS200 devices.

**Comment by adriangith** [comment]
I have the issue as well. It appears to cause the entire homebridge system to become unresponsive for me.
