### ISSUE TITLE
v6.4.0 - Homebridge shows SIGTERM - and reboots constantly

### ISSUE THREAD

**Issue by sw33tT** [plasticrake/homebridge-tplink-smarthome#196]
hello, 

i updated to v6.4.0 and my homebridge setup stopped working.

With v6.4.0 beta 1 i had no issues.

[08/05/2021, 10:56:05] [TplinkSmarthome] Initializing TplinkSmarthome platform...
[08/05/2021, 10:56:05] [TplinkSmarthome] homebridge-tplink-smarthome v6.4.0, node v14.16.1, homebridge v1.3.4, api v2.7
[08/05/2021, 10:56:06] ConfigParseError: Error parsing config
    at Object.parseConfig (/usr/local/lib/node_modules/homebridge-tplink-smarthome/src/config.ts:262:11)
    at new TplinkSmarthomePlatform (/usr/local/lib/node_modules/homebridge-tplink-smarthome/src/platform.ts:70:19)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
[08/05/2021, 10:56:06] Got SIGTERM, shutting down Homebridge...

Thanks for your nice plugin.

**Comment by Infallibleman** [comment]
the latest version of 6.4.0 is causing consistent crashes of the homebridge platform, getting stuck in rolling reboot and crash.

Same Here Below is the error seen when it crashes.

[5/8/2021, 8:10:37 AM] [TPLink-Kasa] homebridge-tplink-smarthome v6.4.0, node v12.22.1, homebridge v1.3.4, api v2.7 [5/8/2021, 8:10:38 AM] ConfigParseError: Error parsing config: devices/0 must be object at Object.parseConfig (/usr/lib/node_modules/homebridge-tplink-smarthome/src/config.ts:259:11) at new TplinkSmarthomePlatform (/usr/lib/node_modules/homebridge-tplink-smarthome/src/platform.ts:70:19) at /usr/lib/node_modules/homebridge/src/server.ts:440:40 at Array.forEach (<anonymous>) at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:372:27) at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:159:29) [5/8/2021, 8:10:38 AM] Got SIGTERM, shutting down Homebridge...

**Had to revert to 6.4.0-beta-1 to get ot to stop.**

**Comment by plasticrake** [comment]
Can you please provide your configuration?

**Comment by Infallibleman** [comment]
"name": "TPLink-Kasa",
    "platform": "TplinkSmarthome",
    "devices": [
        "HS105"
    ],
    "deviceTypes": [
        "plug"

**Comment by plasticrake** [comment]
Change it to just:
```
"name": "TPLink-Kasa",
"platform": "TplinkSmarthome"
```

How you have `devices` is not correct
