### ISSUE TITLE
TCP Timeout when using HS200

### ISSUE THREAD

**Issue by bustinbung** [plasticrake/homebridge-tplink-smarthome#224]
### Expected Behavior

Turning on and off light should happen within 5-10 seconds. 

### Current Behavior

Turning on lights gives "no response" before turning on.
Turning off lights takes about 10 seconds.

### Versions

- **Node**: v16.13.0
- **Homebridge**: v1.3.6
- **OS**: Raspbian GNU/Linux 11 (bullseye) armv7l, kernel v5.10.63-v7+

### Configuration

```json
{
    "name": "TP-Link",
    "addCustomCharacteristics": true,
    "deviceTypes": [
        "plug",
        "bulb"
    ],
    "platform": "TplinkSmarthome"
},
```

### Homebridge Log / Command Output

```
TCP 10.0.0.77:9999 Error: TCP Timeout after 15000ms
10.0.0.77:9999 {"system":{"get_sysinfo":{}}}
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:67:17)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

**Comment by weitieda** [comment]
Same error here with: Node v16.14.0, Npm v8.5.1, Raspbian GNU/Linux Bullseye (11)

Recently I experienced a lot "No response" in HK app, I reboot my pi via GUI sometimes it could fix the "No response" issue. But recently reboot doesn't work so I re-installed the whole homebridge image, after setting all my Kasa accessories up, everything works, but the second morning, it gave me this timeout error again... By the way, all Kasa products works well with Kasa's app. I tried turn on/off in Homebridge GUI "Accessories" panel, the button could be highlighted but will throw the timeout error. 🤔

```
[12/04/2022, 09:53:10] [TplinkSmarthome.API] [Wall Light] device.send() Error: TCP Timeout after 15000ms
192.168.50.47:9999 {"system":{"get_sysinfo":{}}}
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:67:17)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[12/04/2022, 09:53:10] [TplinkSmarthome] [Wall Light] {}
[12/04/2022, 09:53:10] [TplinkSmarthome.API] TCP 192.168.50.123:9999 Error: TCP Timeout after 15000ms
192.168.50.123:9999 {"system":{"get_sysinfo":{}}}
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:67:17)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[12/04/2022, 09:53:10] [TplinkSmarthome.API] [Small Room Ceiling Light] device.send() Error: TCP Timeout after 15000ms
192.168.50.123:9999 {"system":{"get_sysinfo":{}}}
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:67:17)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[12/04/2022, 09:53:10] [TplinkSmarthome] [Small Room Ceiling Light] {}
```
