### ISSUE TITLE
"Error: connect ENETUNREACH" on multiple devices

### ISSUE THREAD

**Issue by salmundo11** [plasticrake/homebridge-tplink-smarthome#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I see errors similar to this for multiple devices, all with the same time stamps, one or two times per day:

```
[22/03/2022, 15:21:21] [TplinkSmarthome] [UPS Monitor] emeter.getRealtime()
[22/03/2022, 15:21:21] [TplinkSmarthome] Error: connect ENETUNREACH 192.168.7.201:9999 - Local (0.0.0.0:0)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -101,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.7.201',
  port: 9999
}
```

### What, if anything, has recently changed?

Updates to the OS to make current, node.js updated to current, npm updated to current.

Router is eero.

### Version

7.0.1

### Node Version

v16.14.2

### Homebridge Version

1.4.0

### Which OS/Platform?

Linux

### Relevant log output

```shell
[22/03/2022, 15:21:21] [TplinkSmarthome.API] TCP 192.168.7.247:9999 Error: connect ENETUNREACH 192.168.7.247:9999 - Local (0.0.0.0:0)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -101,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.7.247',
  port: 9999
}
[22/03/2022, 15:21:21] [TplinkSmarthome.API] TCP 192.168.7.201:9999 Error: connect ENETUNREACH 192.168.7.201:9999 - Local (0.0.0.0:0)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -101,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.7.201',
  port: 9999
}
[22/03/2022, 15:21:21] [TplinkSmarthome.API] TCP 192.168.7.251:9999 Error: connect ENETUNREACH 192.168.7.251:9999 - Local (0.0.0.0:0)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -101,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.7.251',
  port: 9999
}
[22/03/2022, 15:21:21] [TplinkSmarthome.API] TCP 192.168.7.204:9999 Error: connect ENETUNREACH 192.168.7.204:9999 - Local (0.0.0.0:0)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -101,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.7.204',
  port: 9999
}
[22/03/2022, 15:21:21] [TplinkSmarthome.API] [Washing machine monitor] device.send() Error: connect ENETUNREACH 192.168.7.247:9999 - Local (0.0.0.0:0)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -101,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.7.247',
  port: 9999
}
[22/03/2022, 15:21:21] [TplinkSmarthome.API] [UPS Monitor] device.send() Error: connect ENETUNREACH 192.168.7.201:9999 - Local (0.0.0.0:0)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -101,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.7.201',
  port: 9999
}
[22/03/2022, 15:21:21] [TplinkSmarthome.API] [Refrigerator] device.send() Error: connect ENETUNREACH 192.168.7.251:9999 - Local (0.0.0.0:0)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -101,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.7.251',
  port: 9999
}
[22/03/2022, 15:21:21] [TplinkSmarthome.API] [Shed] device.send() Error: connect ENETUNREACH 192.168.7.204:9999 - Local (0.0.0.0:0)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -101,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.7.204',
  port: 9999
}
[22/03/2022, 15:21:21] [TplinkSmarthome] [Washing machine monitor] emeter.getRealtime()
[22/03/2022, 15:21:21] [TplinkSmarthome] Error: connect ENETUNREACH 192.168.7.247:9999 - Local (0.0.0.0:0)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -101,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.7.247',
  port: 9999
}
[22/03/2022, 15:21:21] [TplinkSmarthome] [UPS Monitor] emeter.getRealtime()
[22/03/2022, 15:21:21] [TplinkSmarthome] Error: connect ENETUNREACH 192.168.7.201:9999 - Local (0.0.0.0:0)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -101,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.7.201',
  port: 9999
}
[22/03/2022, 15:21:21] [TplinkSmarthome] [Refrigerator] emeter.getRealtime()
[22/03/2022, 15:21:21] [TplinkSmarthome] Error: connect ENETUNREACH 192.168.7.251:9999 - Local (0.0.0.0:0)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -101,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.7.251',
  port: 9999
}
[22/03/2022, 15:21:21] [TplinkSmarthome] [Shed] emeter.getRealtime()
[22/03/2022, 15:21:21] [TplinkSmarthome] Error: connect ENETUNREACH 192.168.7.204:9999 - Local (0.0.0.0:0)
    at internalConnect (node:net:931:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at node:net:1022:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -101,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.7.204',
  port: 9999
}
```

### Configuration

```json
{
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": false,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome"
        },
```

**Comment by salmundo11** [comment]
These devices are KP115 and KP125.  Other devices are not seeing this issue.

**Comment by salmundo11** [comment]
I downgraded to version 7.0.0, and am no longer seeing this issue.

**Comment by zx81uk** [comment]
I’m seeing exactly the same. It’s cured by rolling back to version 7.0.0 as well.

![1B174EE1-2E3A-465C-BA31-EA8DF3E7E899](https://user-images.githubusercontent.com/64488862/174692626-3d99d3a8-48a1-40db-8956-2a6d5921b02b.jpeg)

**Comment by salmundo11** [comment]
This is what I see with version 7.0.0:

```
[23/06/2022, 16:51:05] [TplinkSmarthome.API] TCP 192.168.7.251:9999 Error: TCP Timeout after 15000ms
192.168.7.251:9999 {"emeter":{"get_realtime":{}}}
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/.pnpm/tplink-smarthome-api@4.1.0/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:67:17)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[23/06/2022, 16:51:05] [TplinkSmarthome.API] [Refrigerator] device.send() Error: TCP Timeout after 15000ms
192.168.7.251:9999 {"emeter":{"get_realtime":{}}}
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/.pnpm/tplink-smarthome-api@4.1.0/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:67:17)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[23/06/2022, 16:51:05] [TplinkSmarthome] [Refrigerator] emeter.getRealtime()
[23/06/2022, 16:51:05] [TplinkSmarthome] Error: TCP Timeout after 15000ms
192.168.7.251:9999 {"emeter":{"get_realtime":{}}}
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/.pnpm/tplink-smarthome-api@4.1.0/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:67:17)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

**Comment by shurikm97** [comment]
Having the same issue and downgrade didnt help.  I see status of all my TP Link devices but can not turn on or off keep getting the same error.  Installed a brand new version of homebridge same issue. I mostly have HS200 and 210 switches other plugins on the same network work fine through HB.

Node.js Version | v16.15.0

[7/2/2022, 10:06:41 AM] [Switches.API] TCP 192.168.1.167:9999 Error: connect EHOSTUNREACH 192.168.1.167:9999
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.167',
  port: 9999


Node.js Version	[v16.15.0](https://homebridge.io/w/JTKEF)
