### ISSUE TITLE
Discovers Devices - No Control

### ISSUE THREAD

**Issue by djs007** [plasticrake/homebridge-tplink-smarthome#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am running Homebridge on a Virtual Machine on a subnet the same as my iPhone and the Kasa devices are on a separate subnet.  The VM has two interfaces and is able to discover and add all the devices to HomeKit without issue within a sub bridge.

When I make a status change to a device it changes in HomeKit but does not communicate to the device and when the refresh happens it goes back to the old state.

Regardless of device I am turning on and off I get an error about color temperature.

### What, if anything, has recently changed?

This is a fresh install on a dedicated VM

### Version

7.0.1

### Node Version

v16.16.0

### Homebridge Version

1.5.0

### Which OS/Platform?

Linux

### Relevant log output

```shell
[9/13/2022, 12:36:12 AM] [homebridge-tplink-smarthome] Error: 
    at ColorTemperature.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at ColorTemperature.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2045:14)
    at ColorTemperature.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1582:21)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at __awaiter (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:114:16)
    at ColorTemperature.Characteristic.handleGetRequest (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:689:38)
    at ColorTemperature.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2207:22)
```

### Configuration

```json
Default config
```

**Comment by djs007** [comment]
To add clarity the log output is from enabling debug.  This is the message before that:

[9/13/2022, 12:36:12 AM] [homebridge-tplink-smarthome] This plugin generated a warning from the characteristic 'Color Temperature': characteristic was supplied illegal value: number 140 exceeded minimum of 154. See https://homebridge.io/w/JtMGR for more info.

**Comment by djs007** [comment]
Looks like I found a solution.  I deleted and re-created the sub-bridge and specifically called out the broadcast for that subnet instead of a multicast it seems to solve the problem.
