### ISSUE TITLE
Move HS-300 to surge protector outlet icon

### ISSUE THREAD

**Issue by roberkane212** [plasticrake/homebridge-tplink-smarthome#303]
### Current Situation

Currently all plugs show separately as individual outlets not all as one

### Proposed Change

That it will show as it is a power strip instead of individual outlets

**Comment by roberkane212** [comment]
I currently have homebridge-tuya installed and have no issue with that plugin showing it
![IMG_1660](https://user-images.githubusercontent.com/44589993/223312234-6440e2f4-4793-4c38-8cd7-b7ce08e27370.png)

**Comment by ZeliardM** [comment]
I was able to create this with the homebridge-meross plugin, I will take a stab at this one and see if I can create a PR.

**Comment by roberkane212** [comment]
@ZeliardM let me know if I can help in anyway

**Comment by ZeliardM** [comment]
I’m going to have to see, I don’t have a HS-300 yet, so while I work on the code I need to get one.

**Comment by ZeliardM** [comment]
I was able to get the basic premise done for this. Had to make api calls in the plugin because the built api doesn't support passing the childId as an argument, but right now I have basic functionality up and working, just need to clean it up and fix some of the status updates in HomeKit. Once I'm finished, I'll push a PR to let them merge it if they're good with it and maybe can get them to update the API to support passing the childId and that may clean it up even more.

**Comment by roberkane212** [comment]
@ZeliardM thats awesome. Again let me know if there’s anything I can do

**Comment by ZeliardM** [comment]
The code has been cleaned up and the PR has been submitted. We will see what the dev says and go from there. Until then, I'm going to keep running my local copy, lol

**Comment by roberkane212** [comment]
@ZeliardM awesome, hopefully he responds to his asap

**Comment by roberkane212** [comment]
@ZeliardM  I wish I knew more coding. I’d get run a local copy myself lol

**Comment by roberkane212** [comment]
@ZeliardM i see you have a forked version of the plugin. Is there anyway for me to install it by chance?

**Comment by ZeliardM** [comment]
I would not as the dev hasn't tested everything and I may have made mistakes. I cannot support it like they did.

**Comment by roberkane212** [comment]
Ok thanks

**Comment by roberkane212** [comment]
@ZeliardM  I have against you saying so installed your fork, however when I changed plug to power strip. It says it’s not supported. I know you can not support your version that’s much. But the power strip this the only item I use with this plugin and would really appreciate your help. If it doesn’t work as well. I will go back to original version

**Comment by ZeliardM** [comment]
What did you change from plug to power strip? The process for my change is to check a box under the HomeKit (Optional) configuration to enable creating a power strip. Leave all the rest of your stuff alone and put it back to plug. That is a reference to his api that I did not change.

**Comment by roberkane212** [comment]
@ZeliardM ok I must have not install yours right. Because I don’t have the option.

**Comment by roberkane212** [comment]
@ZeliardM i will try again

**Comment by roberkane212** [comment]
@ZeliardM did you have to remove the original plugin, to make your changes?

**Comment by ZeliardM** [comment]
No, just need to run the following command from the terminal in the homebridge web console:
npm install ZeliardM/homebridge-tplink-smarthome

Again, I'm not responsible for anything that happens when and if you choose to do this nor will I support any problems you have.

I have told you I don't support this as it is the plugin creators invention and I'm trying to help out but I'm not taking over.

**Comment by roberkane212** [comment]
Yes thank you I appreciate it, and again if there is an issue I will go back to original. How I have ran what you told me in terminal and still don’t have the option. Thank you again for your help. I know your don’t plan to support

**Comment by ZeliardM** [comment]
Did you restart Homebridge or child bridge after you ran the command?

**Comment by roberkane212** [comment]
@ZeliardM yes but when I ran the command I got a few error messages back. So I’m guessing it did not install

**Comment by ZeliardM** [comment]
Most likely, what were the error messages?

**Comment by roberkane212** [comment]
@ZeliardMnpm ERR! code 127
npm ERR! git dep preparation failed
npm ERR! command /opt/homebridge/bin/node /opt/homebridge/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/pi/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > homebridge-tplink-smarthome@8.0.3 prepare
npm ERR! > npm run build
npm ERR! 
npm ERR! 
npm ERR! > homebridge-tplink-smarthome@8.0.3 prebuild
npm ERR! > npm run clean
npm ERR! 
npm ERR! 
npm ERR! > homebridge-tplink-smarthome@8.0.3 clean
npm ERR! > rimraf lib/ build/
npm ERR! sh: 1: rimraf: not found
npm ERR! npm ERR! code 127
npm ERR! npm ERR! path /home/pi/.npm/_cacache/tmp/git-cloneUsurQf
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c npm run build
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in: /home/pi/.npm/_logs/2024-03-20T16_47_49_792Z-debug-0.log

npm ERR! A complete log of this run can be found in: /home/pi/.npm/_logs/2024-03-20T16_47_37_291Z-debug-0.log

**Comment by ZeliardM** [comment]
Ah, I remember. Had to run npm install -g rimraf first. Something in the deployment missing for manually installing.

**Comment by roberkane212** [comment]
@ ok so run npm install-g rimraf. Then run your npm install ZeliardM/homebridge-tplink-smarthome. Right?

**Comment by ZeliardM** [comment]
Yes

**Comment by roberkane212** [comment]
@ZeliardM yes it worked thank you!!!!!

**Comment by ZeliardM** [comment]
Ok, udp worked for me, so it could be a difference in models or something else. But glad to help.

**Comment by roberkane212** [comment]
@ZeliardM it is working wonderful for me right now. Thank you so so much!!! I appreciate all your help and work. I will not be asking for anymore advise as I’m sure you have plugins you actually are apart of. However I very much appreciate you helping me to get that power strip working. I will let you know if I get upd to work, but that’s it. A million thanks, I’ve wanted this for over a year now!!

**Comment by ZeliardM** [comment]
Glad I could help and I can help where I can but specifics would have to wait on the plugin creator. Not sure if udp is required, I use it because of a bunch of errors that come up when it's tcp. I don't use any other custom entries in the plugin or settings, I just leave it all as default, if that helps.

**Comment by roberkane212** [comment]
@ZeliardM i still get error logs, but it works. I don’t know how to get the error logs to go away

**Comment by ZeliardM** [comment]
I got them to go away by switching the transport in the settings to udp. But you said you had to change it to tcp.

**Comment by roberkane212** [comment]
@ZeliardM  I do have one more question for you if you can answer it if not I understand. do you know why I might be gettin this error now?

[TP-LINK_Power Strip_8A5D] device.send() Error: UDP Timeout after 15000ms
10.0.0.25:9999 {"system":{"get_sysinfo":{}}}
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/udp-socket.ts:64:15)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
Error: UDP Timeout after 15000ms
10.0.0.25:9999 {"system":{"get_sysinfo":{}}}
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/udp-socket.ts:64:15)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)

**Comment by ZeliardM** [comment]
Is the transport udp or tcp? I think that's related to that.

**Comment by roberkane212** [comment]
1. UDP, however it does it on both. and didn't do it before. So I thought maybe there was something I was missing. like when I needed to install rimraf

**Comment by ZeliardM** [comment]
Hmm, I haven't seen it on my end so I'm not sure.

**Comment by roberkane212** [comment]
@ZeliardM Ok no problem, I just figured I'd ask. I appreciate you taking the time

**Comment by roberkane212** [comment]
@ZeliardM hey did you removeyoue version of tp link?

**Comment by ZeliardM** [comment]
@roberkane212 yes, I've made my own plug-in, homebridge-kasa-python, instead.

**Comment by roberkane212** [comment]
@ZeliardM ok thank you. Did you implement the power strip?

**Comment by ZeliardM** [comment]
@roberkane212 Yep
