### ISSUE TITLE
TCP Error

### ISSUE THREAD

**Issue by jhk1620** [plasticrake/homebridge-tplink-smarthome#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Getting the error with Kasa Led lighting.

TplinkSmarthome.API] TCP 999.999.9.99:9999 Error: TCP Timeout after 15000ms
999.999.9.999999 {"system":{"get_sysinfo":{}}}
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:67:17)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)

### What, if anything, has recently changed?

None

### Version

v7.0.1

### Node Version

v7.0.1

### Homebridge Version

v4.50.6

### Which OS/Platform?

Linux

### Relevant log output

```shell
TplinkSmarthome.API] TCP 999.999.9.99:9999 Error: TCP Timeout after 15000ms
999.999.9.999999 {"system":{"get_sysinfo":{}}}
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:67:17)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
```

### Configuration

```json
{
    "platform": "TplinkSmarthome",
    "name": "TplinkSmarthome",
    "addCustomCharacteristics": true,
    "_bridge": {
        "port": ,
        "username": ""
    },
    "deviceTypes": [
        "plug",
        "bulb"
    ]
}
```

**Comment by anthonymkz** [comment]
I am also having this issue with two of my HS210 switches

**Comment by anthonymkz** [comment]
Just an update, I was getting this error after about 20 minutes every time I started the plugin. I changed my Timeout to 30 and wait time to 150 in Advanced Settings of the config and so far so good. Not sure which (or both) helped, but I'll update if the error returns.

**Comment by jhk1620** [comment]
Thanks for the info.  Still the same results.


[xxxxxxx] device.send() Error: UDP Timeout after 45000ms
999.999.9.999:9999 {"system":{"get_sysinfo":{}}}
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/udp-socket.ts:64:15)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)

**Comment by anthonymkz** [comment]
You have your settings at UDP not TCP. I would have specified this but your original post says TCP. I haven't gotten this error again since making these changes.

**Comment by anthonymkz** [comment]
Looks like mine as back is well. So I guess this isn't the fix.
________________________________

**Comment by jhk1620** [comment]
Yeah looks like once you restart the bridge then at the point you turn something on it starts up again.  The switches/lights still work.  But just fills up the logs,

**Comment by jhk1620** [comment]
Weird.  No errors now for the past 10-15 minutes now.  Triggering things now thru HomeKit has not triggered any errors

￼

[12/19/2023, 1:26:33 PM] [TplinkSmarthome] [Entertainment TV Lights] Setting On to: true
[12/19/2023, 1:26:41 PM] [TplinkSmarthome] [Entertainment TV Lights] Setting On to: false
[12/19/2023, 1:26:45 PM] [TplinkSmarthome] [Entertainment TV Lights] Setting On to: true
[12/19/2023, 1:26:53 PM] [TplinkSmarthome] [Entertainment TV Lights] Setting On to: false

**Comment by jhk1620** [comment]
Update…..

So it appears that the issue is not with homebridge and the plugin.   I think the actual device is dropping off and on the network.  I have monitored this closer the past few days.   I think the actual devices need an update.   I have unplugged the lights/device and plugged it back in and it fixes the issue for a short time.   Then another one of my devices behalf the same way.  I am using Kasa Light strips on my TV’s.  I go to the app and it shows me the device is offline thus why I am unplugging it,   So that is my take on it.  Over all the initial changes have helped with the overall issue,

**Comment by wdbrady** [comment]
It does not seem to have any functional impact, but is filling up the logs.   Maybe add an option to throttle back the logging on these events could be added?  I have observed the same issue with the devices appearing dropped from the network, but they do seem available when I trigger the events.

**Comment by iceycake** [comment]
I just updated homebridge and the plugs and the smart plug firmware and ran into the exactly issue. In the advanced setting, default is using TCP as transport. Since the timeout error is TCP, I changed to UDP for transport and everything is back as good as old days.
