### ISSUE TITLE
TP-Link Smarthome plugin crashes homebridge when devices go offline

### ISSUE THREAD

**Issue by ydogandjiev** [plasticrake/homebridge-tplink-smarthome#40]
### Expected Behavior
If one of my TP-Link plugs goes offline it shouldn't take my entire homebridge down with it.

### Current Behavior
When one of my TP-Link plugs is disconnected from the power completely it causes an exception to be thrown by the TP-Link Smarthome plugin which in turn takes down the whole homebridge with it.

### Versions

- **Node**: 8.7.0
- **Homebridge**: 0.4.29
- **OS**: Raspbian GNU/Linux 9.1 (stretch)

### Configuration
```
  "platforms": [
    {
      "platform": "TplinkSmarthome",
      "name": "TplinkSmarthome"
    }
  ]
```

### Homebridge Log / Command Output
```
[2017-10-24 15:31:24] [TplinkSmarthome.API] TCP Timeout
[2017-10-24 15:31:24] [TplinkSmarthome.API] [Bedroom Backlight] device.send() Error: TCP Timeout
[2017-10-24 15:31:24] [TplinkSmarthome] [Bedroom Backlight] getSysInfo
[2017-10-24 15:31:24] [TplinkSmarthome] Error: TCP Timeout
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:248:20)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
/usr/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:287
          throw err;
          ^

Error: connect EHOSTUNREACH 192.168.1.229:9999
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
```

**Comment by plasticrake** [comment]
Hi @ydogandjiev, I made a change to a dependency that should properly reject the promise instead of throwing an error. If you uninstall and reinstall this plugin it should pull in the updated dependency (`tplink-smarthome-api@0.20.1`)

**Comment by plasticrake** [comment]
Closing this. Submit a new issue if you still have problems. Thanks!

**Comment by ydogandjiev** [comment]
@plasticrake, looks like it's working great now! No crashes in the last few days. Thank you!
