### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory: already deleted my cachedAccessories

### ISSUE THREAD

**Issue by trippingwalrus** [plasticrake/homebridge-tplink-smarthome#52]
Hello:

I had Homebridge installed awhile ago but it had not been running for the last six months, so this weekend I decided to tackle the issue. I deleted all of my prior installations and just started from scratch. I get to the point to start Homebridge and I get an error as indicated above. I have reset the cached Accessories, but that does not solve the issue. Here is the full output for the startup:

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-1-20 10:57:09] Loaded plugin: homebridge-smartthings
[2018-1-20 10:57:09] Registering platform 'homebridge-smartthings.SmartThings'
[2018-1-20 10:57:09] ---
[2018-1-20 10:57:09] Loaded config.json with 0 accessories and 1 platforms.
[2018-1-20 10:57:09] ---
[2018-1-20 10:57:09] Loading 1 platforms...
[2018-1-20 10:57:09] [SmartThings] Initializing SmartThings platform...
[2018-1-20 10:57:09] [SmartThings] Fetching Smart Things devices.
[2018-1-20 10:57:11] [SmartThings] Device Added - Group switch, Name Backyard Light, ID b7d8831c-44be-4fbd-9b73-049a27e50776
[2018-1-20 10:57:11] [SmartThings] Device Added - Group switch, Name Christmas Lights, ID 4cb61c8a-cb16-49ea-b248-f5fc0a29cff6
[2018-1-20 10:57:11] [SmartThings] Device Added - Group sensor, Name Bedroom Window, ID d2dd6a4b-f7de-4e12-b9a4-133ff23cb47a
[2018-1-20 10:57:11] [SmartThings] Device Added - Group switch, Name Dining Room Light, ID 2fc9e4b7-0f6b-4e0e-982a-b470ec127e51
[2018-1-20 10:57:11] [SmartThings] Device Added - Group switch, Name EV Plug, ID 82a9e493-217d-4a47-8728-dd0b26b0fadd
[2018-1-20 10:57:11] [SmartThings] Device Added - Group switch, Name Entryway Light, ID 51737889-eb7f-4369-b11a-27146d2a0f5a
[2018-1-20 10:57:11] [SmartThings] Device Added - Group sensor, Name Front Door, ID 228bb129-5e43-4ae1-9637-63955fd4ed13
[2018-1-20 10:57:11] [SmartThings] Device Added - Group  button, Name Front Door, ID 69ad0ef1-b756-413d-9575-2eb708937dc6
[2018-1-20 10:57:11] [SmartThings] Device Added - Group locks, Name Front Lock, ID 8ea20776-1496-4874-bffe-acc55f217720
[2018-1-20 10:57:11] [SmartThings] Device Added - Group switch, Name Garage Lights, ID 903107dc-67fc-44b9-820f-d6a088b2cbd0
[2018-1-20 10:57:11] [SmartThings] Device Added - Group lights, Name Guest Room Lamp, ID 8fc83d59-b694-498a-8264-2e73cd8a2b49
[2018-1-20 10:57:11] [SmartThings] Device Added - Group lights, Name Guest Room Lamp Dimmer, ID e3ec18ae-aead-4378-97e6-661be109fa8b
[2018-1-20 10:57:11] [SmartThings] Device Added - Group sensor, Name Kitchen Sink Window, ID 813fe3d1-e5e8-4b62-ac3d-2353d38efd36
[2018-1-20 10:57:11] [SmartThings] Device Added - Group switch, Name Kitchen Table, ID c24e021a-863b-4fc7-880a-bd23b83de993
[2018-1-20 10:57:11] [SmartThings] Device Added - Group sensor, Name Kitchen Window, ID 64d18d56-4237-49ac-9574-d37d8d5e6a60
[2018-1-20 10:57:11] [SmartThings] Device Added - Group switch, Name Outlet Not Working, ID 963bf97b-a5f7-44ae-9350-60acdf4fc243
[2018-1-20 10:57:11] [SmartThings] Device Added - Group switch, Name Outside Backyard, ID 95b43b05-5e04-41f9-8b81-8abd9b7e2876
[2018-1-20 10:57:11] [SmartThings] Device Added - Group switch, Name Outside Garage, ID 8cc5a969-4b19-4631-9046-dff305b70927
[2018-1-20 10:57:11] [SmartThings] Device Added - Group switch, Name Porch Light, ID 8200a6aa-200b-41b5-950f-23de62efb49a
[2018-1-20 10:57:11] [SmartThings] Device Added - Group thermostats, Name Thermostat, ID aef22a53-8967-4290-9cb7-9aeb2c8ecd53
[2018-1-20 10:57:11] [SmartThings] Device Added - Group sensor, Name Back Sliding Door, ID 012b5a69-9060-48af-b36c-55ca9ec8ec2b
[2018-1-20 10:57:11] [SmartThings] Device Added - Group sensor, Name Cinnamon's iPhone, ID 8e5c840b-c229-4089-9292-604ac6060e5c
[2018-1-20 10:57:11] [SmartThings] Device Added - Group sensor, Name Robert's iPhone, ID 6a3b55a7-3f61-44ca-9ae0-72257b8283de
[2018-1-20 10:57:11] [SmartThings] Device Added - Group sensor, Name Riley, ID fe55d312-fd70-47cf-8d7e-44030188bd43
[2018-1-20 10:57:11] [SmartThings] Device Added - Group sensor, Name Garage Side Door, ID b09116d3-34a1-46ab-9889-cfd5003733d1
[2018-1-20 10:57:11] [SmartThings] Device Added - Group sensor, Name Front Door Motion Sensor, ID 3163ff7e-d8ed-4af6-8668-f410bb451dcf
[2018-1-20 10:57:11] [SmartThings] Unknown Capabilities: ["Health Check","Light","Outlet","Relay Switch","Image Capture","Button","Signal Strength","Video Camera","Video Capture","Video Stream","Tone"]
[2018-1-20 10:57:11] [SmartThings] Initializing platform accessory 'Backyard Light'...
[2018-1-20 10:57:11] [SmartThings] Initializing platform accessory 'Christmas Lights'...
[2018-1-20 10:57:11] [SmartThings] Initializing platform accessory 'Bedroom Window'...
[2018-1-20 10:57:11] [SmartThings] Initializing platform accessory 'Dining Room Light'...
[2018-1-20 10:57:11] [SmartThings] Initializing platform accessory 'EV Plug'...
[2018-1-20 10:57:11] [SmartThings] Initializing platform accessory 'Entryway Light'...
[2018-1-20 10:57:11] [SmartThings] Initializing platform accessory 'Front Door'...
[2018-1-20 10:57:11] [SmartThings] Initializing platform accessory 'Front Door'...
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 800a1d7f-0d6d-46d4-b1c9-bff45b57f275
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:377:24)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/lib/node_modules/homebridge-smartthings/index.js:121:4
    at /usr/lib/node_modules/homebridge-smartthings/index.js:98:5
    at /usr/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:94:29
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:45:29)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)

I am just using Homebridge for SmartThings. Thanks.

**Comment by plasticrake** [comment]
This is not the repo for the smartthings plugin, this is for tplink-smarthome. You may want to create an issue for smartthings.
