### ISSUE TITLE
TP-Link KC120 (Indoor Camera) Homebridge Stops Responding

### ISSUE THREAD

**Issue by cps5155** [plasticrake/homebridge-tplink-smarthome#68]
Just got a new TP-Link KC-120 Indoor Camera and hooked it up through Kasa etc. all working well. I went to check the Homebridge setup and saw that it's no longer supporting any of my accessories. Scoured the interwebz and don't seem to find a straight forward answer so here I am --- I understand there might not be support for the TP-Link cameras (yet) through this Homebridge plugin, but would expect a way to _ignore_ unsupported accessories at least. 

Is there a way for me to ignore an IP or MAC through config.json so I can at least continue to use my other accessories? 

I've tried both minimal config.json and with specifying the devices (through IP) for only those I want to add but no luck either way. 

Without the camera (power is unplugged), Homebridge boots & responds to requests fine. Once I plug the camera in, the new device's IP auto-detected and Homebridge stops responding. 

It may be worth noting that I've also got [homebridge-server](https://www.npmjs.com/package/homebridge-server) also installed and running (up until the unrecognized device is added to the network. 

### Expected Behavior
Homebridge continues to respond appropriately even if an upsupported TP-Link device is active on the network

### Current Behavior
Once an unsupport TP-Link device becomes active on the network, Homebridge ceases to respond for any app (TP-Link related or not)

### Steps to Reproduce (for bugs)
Have Homebridge setup with multiple accessories (TP-Link and other)
Add an unsupported TP-Link camera to the network
Homebridge will stop responding

### Versions

- **Node**:  v6.9.5
- **Homebridge**: 0.4.43
- **OS**:  Linux armv61 4.14.34 (raspberry Pi)

### Configuration
```
"platforms": [
        {
            "platform" : "TplinkSmarthome",
            "name" : "TplinkSmarthome",
            "devices":[
                { "host": "192.168.0.61" },
                { "host": "192.168.0.62" },
                { "host": "192.168.0.63" },
                { "host": "192.168.0.64"}
            ]
        }
]
```
or (minimal) same result
```
"platforms": [
        {
            "platform" : "TplinkSmarthome",
            "name" : "TplinkSmarthome"
        }
]
```
### Homebridge Log / Command Output
_Camera is off, Homebridge starts successfully_
###/var/log/homebridge.log...
```
[8/28/2018, 12:44:31 AM] Homebridge is running on port 51826.
<< Turn on the camera, gets assigned an IP from DHCP >>
[8/28/2018, 12:46:18 AM] [TplinkSmarthome] New Device Online: [undefined] device [undefined] 192.168.0.59 9999
```
_Homebridge stops responding entirely_
_Same timeframe, error log_
###/var/log/homebridge.err
```
Tue, 28 Aug 2018 00:46:09 GMT EventedHTTPServer [::ffff:192.168.0.22] Writing pending HTTP event data
/opt/node/lib/node_modules/homebridge-tplink-smarthome/lib/platform.js:94
    if (device.deviceId == null || device.deviceId.length === 0) throw new Error('Missing deviceId');
                                                                 ^

Error: Missing deviceId
    at TplinkSmarthomePlatform.addAccessory (/opt/node/lib/node_modules/homebridge-tplink-smarthome/lib/platform.js:94:72)
    at Client.TplinkSmarthomePlatform.client.on (/opt/node/lib/node_modules/homebridge-tplink-smarthome/lib/platform.js:60:12)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at Client.emit (/opt/node/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:361:18)
    at Client.createOrUpdateDeviceFromSysInfo (/opt/node/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:697:12)
    at Socket.<anonymous> (/opt/node/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:638:16)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:550:8)

```

**Comment by cps5155** [comment]
Surprisingly the direct api invokation of `getSysInfo` on the IP didn't work (not response on CLI), but `tplink-smarthome-api search -D` did find some information on the camera. See below - I removed _mac_ and _mic_mac_ but can send in a PM if needed.

```
client.startDiscovery(): socket: message From: 10.0.0.2 9999 Message: 
{
    "system":
    {
        "get_sysinfo":
        {
            "err_code": 0,
            "system":
            {
                "sw_ver": "2.2.11 Build 20180806 rel.57679",
                "hw_ver": "1.0",
                "model": "KC120(US)",
                "hwId": "CB7107D55354DEEFA98A18A06C4B65CD",
                "oemId": "69CC720CF36BB0DBB673B7AA7AAE9CD6",
                "deviceId": "801ADED8890DF96AC9D44E43A98349E81A2B5491",
                "dev_name": "Kasa Cam",
                "type": "IOT.IPCAMERA",
                "alias": "Front Camera",
                "mic_mac": "NORMALIZED_MAC",
                "mac": "REMOVED",
                "longitude": REMOVED,
                "latitude": REMOVED,
                "rssi": -47,
                "system_time": 1536698533,
                "led_status": "off",
                "updating": false,
                "status": "configured",
                "resolution": "720P",
                "camera_switch": "on",
                "bind_status": true,
                "account_id": "@cps5155@github.com",
                "last_activity_timestamp": 1536660009
            }
        }
    }
}
device.constructor(
{
    "client": "not shown",
    "host": "10.0.0.2",
    "port": 9999,
    "sysInfo":
    {
        "err_code": 0,
        "system":
        {
            "sw_ver": "2.2.11 Build 20180806 rel.57679",
            "hw_ver": "1.0",
            "model": "KC120(US)",
            "hwId": "CB7107D55354DEEFA98A18A06C4B65CD",
            "oemId": "69CC720CF36BB0DBB673B7AA7AAE9CD6",
            "deviceId": "801ADED8890DF96AC9D44E43A98349E81A2B5491",
            "dev_name": "Kasa Cam",
            "type": "IOT.IPCAMERA",
            "alias": "Front Camera",
            "mic_mac": "NORMALIZED_MAC",
            "mac": "MAC_REMOVED",
            "longitude": REMOVED,
            "latitude": REMOVED,
            "rssi": -47,
            "system_time": 1536698533,
            "led_status": "off",
            "updating": false,
            "status": "configured",
            "resolution": "720P",
            "camera_switch": "on",
            "bind_status": true,
            "account_id": "@cps5155@github.com",
            "last_activity_timestamp": 1536660009
        }
    },
    "defaultSendOptions":
    {
        "timeout": 5000
    }
})
```

For what it's worth, I hadn't tried clearing my cached accessories nor persist/ items after swapping my config between minimal and devices configuration. I may also attempt to try the MAC whitelist config as well to see if that helps.
