### ISSUE TITLE
Characteristics not work

### ISSUE THREAD

**Issue by ghost** [plasticrake/homebridge-tplink-smarthome#69]
### Expected Behavior

To see W and kWh in the Eve App

### Current Behavior
When I add "addCustomCharacteristics": true to config.json, I get the error message to read below. If I remove the line then homebridge starts without problems

The same applies to the following Characteristics:

- OutletInUse (based on energy monitoring)
- Volts (Custom)
- Amperes (Custom)
- Watts (Custom)
- VoltAmperes (Custom)
- KilowattHours (Custom)
- KilowattVoltAmpereHour (Custom)

### Steps to Reproduce (for bugs)

Same as Current Behavior
### Versions

- **Node**: v8.11.4
- **Homebridge**: 0.4.44
- **OS**: Raspbian GNU/Linux 9 with Kernel 4.14.52-v7+

### Configuration

```json
{
    "bridge": {
        "name": "Raspberry-Pi-Homebridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 51826,
        "pin": "031-45-154"
    },

    "platforms": [{
		"platform": "TplinkSmarthome",
		"name": "TplinkSmarthome"
                "addCustomCharacteristics": true,
    }]    
}

```

### Homebridge Log / Command Output
```
[2018-9-3 19:15:11] There was a problem reading your config.json file.
[2018-9-3 19:15:11] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2018-9-3 19:15:11] 
/usr/lib/node_modules/homebridge/lib/server.js:213
    throw err;
    ^

SyntaxError: Unexpected token { in JSON at position 258
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:207:19)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:56:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:28:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by plasticrake** [comment]
You have a comma in the wrong place. Should be: 
```json
"name": "TplinkSmarthome",
"addCustomCharacteristics": true
```
