### ISSUE TITLE
Error using KL110 Bulb

### ISSUE THREAD

**Issue by vtcajones** [plasticrake/homebridge-tplink-smarthome#81]
I'm using 4.0.0 and I just added a KL110 bulb, whenever homebridge starts now, it crashes with this error:

/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/homekit-device/index.js:88
    if (typeof c.updateCallback === 'function') {
                 ^

TypeError: Cannot read property 'updateCallback' of undefined
    at HomeKitDeviceBulb.fireCharacteristicUpdateCallback (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/homekit-device/index.js:88:18)
    at Bulb.tplinkDevice.on (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/homekit-device/bulb.js:66:14)
    at Bulb.emit (events.js:182:13)
    at Lighting.emitEvents (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/bulb/lighting.js:90:17)
    at Lighting.set lightState [as lightState] (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/bulb/lighting.js:40:10)
    at Bulb.set sysInfo [as sysInfo] (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/bulb/index.js:144:30)
    at process (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:708:24)
    at Client.createOrUpdateDeviceFromSysInfo (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:734:7)
    at Socket.socket.on (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:654:14)
    at Socket.emit (events.js:182:13)

**Comment by plasticrake** [comment]
Please fill out the issue template when creating an issue here. I need to know the versions and startup log output
