### ISSUE TITLE
Error using KL110 Bulb

### ISSUE THREAD

**Issue by vtcajones** [plasticrake/homebridge-tplink-smarthome#82]
### Expected Behavior
The plugin shouldn't crash

### Current Behavior
The plugin crashes

### Steps to Reproduce (for bugs)
Run homebridge

### Versions

- **Node**:     v10.12.0
- **Homebridge**: 0.4.46
- **OS**:         MacOS 10.14.3 (18D109)

### Configuration

```
  "platforms": [{
	  "platform": "TplinkSmarthome",
	  "name": "TplinkSmarthome"
	}]
```

### Homebridge Log / Command Output
```
Setup Payload:
X-HM://0023ISYWY26G3
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
[2/13/2019, 2:49:20 PM] Homebridge is running on port 51826.
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] New Device Online: [Office Tall Light] bulb [80129E6642FCE65C03299391AF12C88B1819998A] 192.168.1.198 9999
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] Adding: [Office Tall Light] bulb [80129E6642FCE65C03299391AF12C88B1819998A]
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] New Device Online: [Office Accent Light] bulb [8012D894F64C7C575A7066EAD632F37A1813950D] 192.168.1.197 9999
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] Adding: [Office Accent Light] bulb [8012D894F64C7C575A7066EAD632F37A1813950D]
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] New Device Online: [Office Small] bulb [80127A36158D4EB90ADCEB3049F5D98B1A4CF926] 192.168.1.182 9999
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] Adding: [Office Small] bulb [80127A36158D4EB90ADCEB3049F5D98B1A4CF926]
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] New Device Online: [Side External] plug [80068EADF8256B3D15625AA40B6F221417D6E7B6] 192.168.1.204 9999
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] Adding: [Side External] plug [80068EADF8256B3D15625AA40B6F221417D6E7B6]
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] New Device Online: [Den Accent Light] bulb [8012B7CE60CCE97988713354842B601F18136337] 192.168.1.158 9999
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] Adding: [Den Accent Light] bulb [8012B7CE60CCE97988713354842B601F18136337]
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] New Device Online: [Den Right Light] bulb [80124D21BAA662928A2E9F475073043618144BDA] 192.168.1.168 9999
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] Adding: [Den Right Light] bulb [80124D21BAA662928A2E9F475073043618144BDA]
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] New Device Online: [Living Room Right Light] bulb [8012EA5F094BCF26C2EC7FE78BA4A0EE180F48F1] 192.168.1.243 9999
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] Adding: [Living Room Right Light] bulb [8012EA5F094BCF26C2EC7FE78BA4A0EE180F48F1]
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] New Device Online: [Den Left Light] bulb [80128B6C09338E5CDB325C024C7EA814180E02F1] 192.168.1.169 9999
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] Adding: [Den Left Light] bulb [80128B6C09338E5CDB325C024C7EA814180E02F1]
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] New Device Online: [Living Room Left Light] bulb [8012F52A95EF018C08A30514DF0B188B1818CE7F] 192.168.1.174 9999
[2/13/2019, 2:49:20 PM] [TplinkSmarthome] Adding: [Living Room Left Light] bulb [8012F52A95EF018C08A30514DF0B188B1818CE7F]
/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/homekit-device/index.js:88
    if (typeof c.updateCallback === 'function') {
                 ^

TypeError: Cannot read property 'updateCallback' of undefined
    at HomeKitDeviceBulb.fireCharacteristicUpdateCallback (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/homekit-device/index.js:88:18)
    at Bulb.tplinkDevice.on (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/homekit-device/bulb.js:66:14)
    at Bulb.emit (events.js:182:13)
    at Lighting.emitEvents (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/bulb/lighting.js:90:17)
    at Lighting.set lightState [as lightState] (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/bulb/lighting.js:40:10)
    at Bulb.set sysInfo [as sysInfo] (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/bulb/index.js:144:30)
    at process (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:708:24)
    at Client.createOrUpdateDeviceFromSysInfo (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:734:7)
    at Socket.socket.on (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:654:14)
    at Socket.emit (events.js:182:13)
```

**Comment by plasticrake** [comment]
Is the Living Room Left Light the only KL110 device? What models are the other bulbs?

**Comment by vtcajones** [comment]
So, actually the Office Small is the only KL110 device. All the others are LB100's including the Living Room Left Light

**Comment by vtcajones** [comment]
The error occurs 1 - 2 seconds after homebridge finishes initializing. So it's not like it errors immediately after reaching
` [TplinkSmarthome] Adding: [Living Room Left Light] bulb [8012F52A95EF018C08A30514DF0B188B1818CE7F]`

Living Room Left Light is just the last device to be added

**Comment by plasticrake** [comment]
I couldn't reproduce the issue you were having, but I think I was able to fix it. Try v4.0.1

**Comment by vtcajones** [comment]
Yes, sir. That fixed it. It no longer crashes under v4.0.1
