### ISSUE TITLE
device.send() Error: UDP Timeout

### ISSUE THREAD

**Issue by PaRkThEcAr** [plasticrake/homebridge-tplink-smarthome#86]
Hello! so i seem to be having an issue when i try to change a scene in home through Homebridge. these errors happen when i change to a scene that has different colors from the standard white. i will post my Config.json and the errors. i also get these errors when i try to change the color on an individual bulb through home.. 

these errors do not populate when i try to turn on the bulbs. and i can change some of the colors through siri (ex. "hey siri, change the lights to red")

'},
		{
			"platform": "TplinkSmarthome",
			"name": "TplinkSmarthome",
			"timeout": "60"
		},
		{
'

[6/10/2019, 1:05:44 PM] [TplinkSmarthome.API] UDP Timeout
[6/10/2019, 1:05:44 PM] [TplinkSmarthome.API] [Office] device.send() Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:05:44 PM] [TplinkSmarthome] [Office] 
[6/10/2019, 1:05:44 PM] [TplinkSmarthome] Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:05:44 PM] [TplinkSmarthome.API] UDP Timeout
[6/10/2019, 1:05:44 PM] [TplinkSmarthome.API] [Family room 2] device.send() Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:05:44 PM] [TplinkSmarthome] [Family room 2] 
[6/10/2019, 1:05:44 PM] [TplinkSmarthome] Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:05:44 PM] [TplinkSmarthome.API] UDP Timeout
[6/10/2019, 1:05:44 PM] [TplinkSmarthome.API] [Bedroom 1] device.send() Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:05:44 PM] [TplinkSmarthome] [Bedroom 1] 
[6/10/2019, 1:05:44 PM] [TplinkSmarthome] Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:05:44 PM] [TplinkSmarthome.API] UDP Timeout
[6/10/2019, 1:05:44 PM] [TplinkSmarthome.API] [Bedroom 1] device.send() Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:05:44 PM] [TplinkSmarthome] [Bedroom 1] 
[6/10/2019, 1:05:44 PM] [TplinkSmarthome] Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:05:44 PM] [TplinkSmarthome.API] UDP Timeout
[6/10/2019, 1:05:44 PM] [TplinkSmarthome.API] [Bedroom 2] device.send() Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:05:44 PM] [TplinkSmarthome] [Bedroom 2] 
[6/10/2019, 1:05:44 PM] [TplinkSmarthome] Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:05:44 PM] [TplinkSmarthome.API] UDP Timeout
[6/10/2019, 1:05:44 PM] [TplinkSmarthome.API] [Bedroom 2] device.send() Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:05:44 PM] [TplinkSmarthome] [Bedroom 2] 
[6/10/2019, 1:05:44 PM] [TplinkSmarthome] Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:05:44 PM] [TplinkSmarthome.API] UDP Timeout
[6/10/2019, 1:05:44 PM] [TplinkSmarthome.API] [Family room 1] device.send() Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:05:44 PM] [TplinkSmarthome] [Family room 1] 
[6/10/2019, 1:05:44 PM] [TplinkSmarthome] Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:05:44 PM] [TplinkSmarthome.API] UDP Timeout
[6/10/2019, 1:05:44 PM] [TplinkSmarthome.API] [Family room 1] device.send() Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:05:44 PM] [TplinkSmarthome] [Family room 1] 
[6/10/2019, 1:05:44 PM] [TplinkSmarthome] Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:06:47 PM] [TplinkSmarthome.API] UDP Timeout
[6/10/2019, 1:06:47 PM] [TplinkSmarthome.API] [Family room 2] device.send() Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:06:47 PM] [TplinkSmarthome] [Family room 2] 
[6/10/2019, 1:06:47 PM] [TplinkSmarthome] Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:06:47 PM] [TplinkSmarthome.API] UDP Timeout
[6/10/2019, 1:06:47 PM] [TplinkSmarthome.API] [Family room 2] device.send() Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:06:47 PM] [TplinkSmarthome] [Family room 2] 
[6/10/2019, 1:06:47 PM] [TplinkSmarthome] Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:06:47 PM] [TplinkSmarthome.API] UDP Timeout
[6/10/2019, 1:06:47 PM] [TplinkSmarthome.API] [Bedroom 1] device.send() Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:06:47 PM] [TplinkSmarthome] [Bedroom 1] 
[6/10/2019, 1:06:47 PM] [TplinkSmarthome] Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:06:47 PM] [TplinkSmarthome.API] UDP Timeout
[6/10/2019, 1:06:47 PM] [TplinkSmarthome.API] [Bedroom 1] device.send() Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:06:47 PM] [TplinkSmarthome] [Bedroom 1] 
[6/10/2019, 1:06:47 PM] [TplinkSmarthome] Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:06:47 PM] [TplinkSmarthome.API] UDP Timeout
[6/10/2019, 1:06:47 PM] [TplinkSmarthome.API] [Bedroom 2] device.send() Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:06:47 PM] [TplinkSmarthome] [Bedroom 2] 
[6/10/2019, 1:06:47 PM] [TplinkSmarthome] Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:06:47 PM] [TplinkSmarthome.API] UDP Timeout
[6/10/2019, 1:06:47 PM] [TplinkSmarthome.API] [Bedroom 2] device.send() Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:06:47 PM] [TplinkSmarthome] [Bedroom 2] 
[6/10/2019, 1:06:47 PM] [TplinkSmarthome] Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:06:47 PM] [TplinkSmarthome.API] UDP Timeout
[6/10/2019, 1:06:47 PM] [TplinkSmarthome.API] [Family room 1] device.send() Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:06:47 PM] [TplinkSmarthome] [Family room 1] 
[6/10/2019, 1:06:47 PM] [TplinkSmarthome] Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:06:47 PM] [TplinkSmarthome.API] UDP Timeout
[6/10/2019, 1:06:47 PM] [TplinkSmarthome.API] [Family room 1] device.send() Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[6/10/2019, 1:06:47 PM] [TplinkSmarthome] [Family room 1] 
[6/10/2019, 1:06:47 PM] [TplinkSmarthome] Error: UDP Timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:144:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

**Comment by cimaszewski** [comment]
hi there @PaRkThEcAr,

Have you made any progress with this issue?

I'm assuming the color change you're talking about is related to the smart wifi LED bulb, I just started to experience the same UDP timeout issue with the LB130.  The comms for these bulbs used to work flawlessly for me.

I just started experiencing the same issue, specifically when issuing HomeKit commands through the Home App or Siri on an iOS device or a OSX device.

Strangely enough, the color changing works perfectly fine for me using Siri commands on HomePod, provided I'm not focused on the device in the HomeApp on an iOS or OSX device when I issue the command.

Basically, what I've noticed - I'll get the UDP timeout in this scenario and I'll see the light turn to the requested color then fade to the "default" white color.

I can't really say when this issue started happening, as I generally control the color with Scenes and Automations using the HomePod device, which only exhibits this issue in certain scenarios.

I'm speculating one of three items is occurring for me:
- there's an issue with the TPLink firmware version (I have version 1.8.6) on both of my bulbs - I'm hoping that I can likely debug this a bit by sniffing my network and comparing what homebridge is sending to the device vs. what the tp-link app is sending to the device
- the plugin is returning an error due to the UDP timeout in the scenario with the HomeApp, it catches the error and reverts to a default color.
- My wireless mesh network is dropping UDP packets across the nodes.

**Comment by PaRkThEcAr** [comment]
@cimaszewski sorry for my late reply. for me, it mostly happens when i turn on a scene in the Home App. i have 3 scenes i regularly use. one for when my wife gets home, one for a bunch of fun colors when i get home, and one for when i want to watch a movie. when i select any of these scenes from the home app, or if an automation is to trigger them, i often see this in the app. 
![IMG_2030](https://user-images.githubusercontent.com/39027440/63531429-bbcebb80-c4c5-11e9-8d0d-11a16cbd2892.jpg)
![IMG_2031](https://user-images.githubusercontent.com/39027440/63531430-bbcebb80-c4c5-11e9-919a-46733f9ee494.jpg)

which is odd. but when i remote into my homebridge server, i see this in the terminal.
![Screen Shot 2019-08-22 at 10 09 11 AM](https://user-images.githubusercontent.com/39027440/63531462-cbe69b00-c4c5-11e9-89d5-24031775fae8.png)

generally, my light control is done through my Google Home, but i use my automations for when i or my wife arrive home. so the issue hasnt resolved. i will see if my lights have an update.. but i havent seen an update post for any of my bulbs since i first got them.

**Comment by PaRkThEcAr** [comment]
Also, is there a particular reason for when a scene doesnt change all the colors properly? I have one that should change all the lights to specific colors. usually one or two lights won’t accept the scene change but HomeKit says the scene is applied. When I check the scene, everything is configured correctly.

**Comment by clovenlife** [comment]
also experiencing this issue. Manual color change is not affected, only scenes and preset colors

**Comment by PaRkThEcAr** [comment]
Yeah, I got so fed up with nothing changing for this, that I ended up selling my lights for Philips Hue bulbs. I still have my plugs though. This plug in works AMAZING for those. 

Does anyone have an active solution for these?

**Comment by ksmulders** [comment]
Got the same problem. Also responded to another topic in this project. Anyone found a solution?

**Comment by plasticrake** [comment]
There have been lots of improvements around this in the newest version of the plugin (v5.2.0). Please try it and let me know if it helps.
