### ISSUE TITLE
Constant TCP Timeout Errors

### ISSUE THREAD

**Issue by 400HPMustang** [plasticrake/homebridge-tplink-smarthome#88]
### Expected Behavior
Lights should respond fairly quickly to home kit, turn off and on when triggered

### Current Behavior
Lights are sluggish, slow to respond and/or just unresponsive all together

### Steps to Reproduce (for bugs)
Add HS100 plugs or LB100 bulbs to Homebridge?

### Versions

- **Node**:       10.16.2
- **Homebridge**: 0.4.5.0
- **OS**:         Windows 10 x64

### Configuration

```
{
            "platform": "TplinkSmarthome",
            "name": "TplinkSmarthome"
        },
```

### Homebridge Log / Command Output

```
[8/12/2019, 7:11:23 AM] [Config] Console v4.5.2 is listening on :: port 8008
[8/12/2019, 7:12:54 AM] [TplinkSmarthome.API] TCP Timeout
[8/12/2019, 7:12:54 AM] [TplinkSmarthome.API] TCP Timeout
[8/12/2019, 7:12:54 AM] [TplinkSmarthome.API] [Garage Door Left] device.send() Error: TCP Timeout
[8/12/2019, 7:12:54 AM] [TplinkSmarthome.API] [Garage Door Left] device.send() Error: TCP Timeout
[8/12/2019, 7:12:54 AM] [TplinkSmarthome] [Garage Door Left]
[8/12/2019, 7:12:54 AM] [TplinkSmarthome] Error: TCP Timeout
    at Timeout.setTimeout [as _onTimeout] (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-tplink-smarthome\node_modules\tplink-smarthome-api\lib\client.js:228:20)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[8/12/2019, 7:12:54 AM] [TplinkSmarthome] [Garage Door Left]
[8/12/2019, 7:12:54 AM] [TplinkSmarthome] Error: TCP Timeout
    at Timeout.setTimeout [as _onTimeout] (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-tplink-smarthome\node_modules\tplink-smarthome-api\lib\client.js:228:20)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[8/12/2019, 7:15:01 AM] [TplinkSmarthome.API] TCP Timeout
[8/12/2019, 7:15:01 AM] [TplinkSmarthome.API] TCP Timeout
[8/12/2019, 7:15:01 AM] [TplinkSmarthome.API] [Garage Door Left] device.send() Error: TCP Timeout
[8/12/2019, 7:15:01 AM] [TplinkSmarthome.API] [Garage Door Left] device.send() Error: TCP Timeout
[8/12/2019, 7:15:01 AM] [TplinkSmarthome] [Garage Door Left]
[8/12/2019, 7:15:01 AM] [TplinkSmarthome] Error: TCP Timeout
    at Timeout.setTimeout [as _onTimeout] (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-tplink-smarthome\node_modules\tplink-smarthome-api\lib\client.js:228:20)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[8/12/2019, 7:15:01 AM] [TplinkSmarthome] [Garage Door Left]
[8/12/2019, 7:15:01 AM] [TplinkSmarthome] Error: TCP Timeout
    at Timeout.setTimeout [as _onTimeout] (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-tplink-smarthome\node_modules\tplink-smarthome-api\lib\client.js:228:20)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by kwalkington** [comment]
I'm getting the same thing.

**Comment by Calprainn** [comment]
Same here. Config runs two/three in row without any issues. Since yesterday I'm getting also TCP timeouts. Ironically just for one of my four HS100 plugs. I don't get it. 🤷🏻‍♀️

**Comment by kwalkington** [comment]
Any update about this?  I deleted the plugin as it was unusable.

**Comment by 400HPMustang** [comment]
I haven't had any more instances of the timeouts in my logs that I've seen BUT since I posted this I've removed all but one TP-Link device from my home. I just have one plug left over in my setup.

**Comment by Wiejeben** [comment]
Looks like this is obviously coming from https://github.com/plasticrake/tplink-smarthome-api. Someone already made a pull request with a potential fix, lets hope this solves the turning off and on again of your TP-Link accessories.

https://github.com/plasticrake/tplink-smarthome-api/pull/95

**Comment by anubisvic** [comment]
Also suffering from this issue, really hope what the pull request @Wiejeben mentioned would fix this issue. For my situation, it only occurs to one of my switches that could be in a wifi dead zone.

**Comment by lwang-ca** [comment]
I had the same TCP Timeout issue recently (has been running fine for a couple weeks and suddenly the issue started 2 days ago)
Restarting homebridge did not help, restarting my Paspberry Pi 4 did not help. I had to restart my router in order to fix the issue.
Then today my issue was fixed by defining the Broadcast address to match my router's subnet mask in Settings -> Optional Configuration.
Hope this helps!

**Comment by aanon4** [comment]
I've been kicking this problem around for a few days after I added an HS300 and everything started timing out. Looking though the debugging (which is mostly in the -api library) I see socket.connect calls being made but the callback never happens because, I assume, the connection is never completed by the HS300. It seems to happen when there's a lot of activity, so perhaps the tplink devices can only handle so many incoming connections at a time, and drop other on the floor if there's too many? I'm testing a hack in a copy of the code currently so see if forcing a one-at-a-time queue when calling devices improves reliability.

**Comment by aanon4** [comment]
Another observation here is that the discovery timer is 10 seconds by default, but the connection timeout is 15 seconds; so when TCP starts acting up on a device, the discovery pings starts up more and more TCP connections because each discovery cycle generates an emeter update per plug (not sure why that code is there, but it is) and these can get stuck timing out. On the HS300 (what I have) this generates 6 sets of calls, one for each plug on the strip. This doesnt seem to be helping things recover. So maybe bumping the pollingInterval to something like 60 seconds might help things.

**Comment by DrFunkelstein** [comment]
I wanted to add that I'm having the same problem. Can't seem to identify what leads up to the errors. I only have 2 total devices (both smart outlets) and am only having this problem with one of them.

**Comment by 400HPMustang** [comment]
Going to close this out since I don't have any TPLink devices on my network anymore.
